export default function Head() {
  return (
    <>
      <title>Cycling Sneak Peek</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
    </>
  );
}
